version: 2.1

jobs:
  deploy:
    docker:
      - image: gcr.io/google.com/cloudsdktool/cloud-sdk:348.0.0
    working_directory: ~/mozilla/firefox-translations-models
    steps:
      - run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
          apt-get install git-lfs
          git lfs install
      - checkout
      - run: |
          echo ${GCLOUD_UPLOADER_KEY} | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gzip -dr */*/*.gz
          gsutil -m cp -rZn prod/* gs://bergamot-models-sandbox/${CIRCLE_TAG}/
          gsutil -m cp -rZn dev/* gs://bergamot-models-sandbox/${CIRCLE_TAG}/
  evaluate:
    machine:
      image: ubuntu-2004:202104-01
    working_directory: ~/mozilla/firefox-translations-models
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          sudo git lfs install
      - checkout
      - run: |
          bash evaluation/update.sh
      - store_artifacts:
          path: evaluation/prod
      - store_artifacts:
          path: evaluation/dev
# todo: commit results when on main
#      - run: |
#          if [ $CIRCLE_BRANCH == main ]; then
#              git config user.email "username@mydomain.com"
#              git config user.name "My Name"
#              git add evaluation/*/*/*.bleu
#              git add evaluation/*/img/*.png
#              git add evaluation/*/results.md
#              git commit -m "Update evaluation results [skip ci]"
#              git push
#          fi

workflows:
  version: 2
  ci:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d*\.\d*\.\d*/
      - evaluate
