version: 2.1

jobs:
  deploy:
    docker:
      - image: gcr.io/google.com/cloudsdktool/cloud-sdk:348.0.0
    working_directory: ~/mozilla/firefox-translations-models
    steps:
      - run: |
          echo "Installing git lfs"
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
          apt-get install git-lfs
          git lfs install
      - checkout
      - run: |
          echo "Uploading to GCS"
          echo ${GCLOUD_UPLOADER_KEY} | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gzip -dr */*/*.gz
          gsutil -m cp -rZn prod/* gs://bergamot-models-sandbox/${CIRCLE_TAG}/
          gsutil -m cp -rZn dev/* gs://bergamot-models-sandbox/${CIRCLE_TAG}/
  evaluate:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: xlarge
    working_directory: ~/mozilla/firefox-translations-models
    steps:
      - run: |
          echo "Installing git lfs"
          sudo apt-get update
          sudo apt-get install -y git-lfs
          sudo git lfs install
      - checkout
      - run: |
          echo "Removing bergamot evaluation results for updated models
          git diff --name-only main |
          grep "models/" |
          python3 -c "import sys; import glob; \
          from signal import signal, SIGPIPE, SIG_DFL; \
          signal(SIGPIPE, SIG_DFL); \
          paths=[ '/'.join(['evaluation'] + x.split('/')[1:3]) for x in sys.stdin.readlines()]; \
          sys.stdout.writelines([g+'\n' for path in paths for g in glob.glob(f'{path[:-2]}-{path[-2:]}/*.bergamot.*.bleu') ])" |
          xargs rm -f
      - run: |
          echo "Running evaluation"
          bash evaluation/update.sh
      - run: |
          echo "Show results"
          git add evaluation/*/*/*.bleu
          git diff --staged evaluation/*/*/*.bleu
      - store_artifacts:
          path: evaluation/prod
      - store_artifacts:
          path: evaluation/dev
# todo: commit results when on main
#      - run: |
#          if [ $CIRCLE_BRANCH == main ]; then
#              git config user.email "username@mydomain.com"
#              git config user.name "My Name"
#              git add evaluation/*/*/*.bleu
#              git add evaluation/*/img/*.png
#              git add evaluation/*/results.md
#              git commit -m "Update evaluation results [skip ci]"
#              git push
#          fi

workflows:
  version: 2
  ci:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d*\.\d*\.\d*/
      - evaluate
